'use client'

import React, { useCallback, useState } from 'react'
import { FileDown, Loader2, CheckCircle2 } from 'lucide-react'

interface AIPDFDownloadProps {
  /** The markdown text content to export as PDF */
  content: string
  /** Optional suggested filename (without extension) */
  filename?: string
}

/**
 * AIPDFDownload — renders a "Download as PDF" button for AI-generated document content.
 *
 * Uses an iframe + window.print() approach with carefully styled print CSS
 * to produce a clean, professional-looking PDF from the AI's markdown response.
 * No third-party PDF library needed — works natively in all modern browsers.
 */
export default function AIPDFDownload({ content, filename = 'ai-document' }: AIPDFDownloadProps) {
  const [status, setStatus] = useState<'idle' | 'generating' | 'done'>('idle')

  const handleDownload = useCallback(() => {
    setStatus('generating')

    // Convert markdown-ish text to styled HTML for printing
    const htmlContent = markdownToHTML(content)

    // Build a complete, print-ready HTML document
    const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${filename}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Inter', 'Segoe UI', sans-serif;
      font-size: 11pt;
      line-height: 1.7;
      color: #1a1a2e;
      background: white;
      padding: 0;
    }

    .page {
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 48px;
    }

    /* Watermark header */
    .watermark {
      text-align: center;
      font-size: 8pt;
      color: #9ca3af;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 10px;
      margin-bottom: 24px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }

    h1 { font-size: 22pt; font-weight: 700; color: #1e1b4b; margin-bottom: 12px; margin-top: 24px; line-height: 1.3; }
    h2 { font-size: 16pt; font-weight: 600; color: #312e81; margin-bottom: 10px; margin-top: 22px; padding-bottom: 4px; border-bottom: 1px solid #e0e7ff; }
    h3 { font-size: 13pt; font-weight: 600; color: #4338ca; margin-bottom: 8px; margin-top: 18px; }
    h4 { font-size: 11pt; font-weight: 600; color: #4f46e5; margin-bottom: 6px; margin-top: 14px; }

    p { margin-bottom: 10px; }

    ul, ol { padding-left: 24px; margin-bottom: 10px; }
    li { margin-bottom: 4px; }

    strong { font-weight: 600; color: #111827; }
    em { font-style: italic; color: #374151; }

    code {
      background: #f3f4f6;
      border: 1px solid #e5e7eb;
      border-radius: 3px;
      padding: 1px 5px;
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #4338ca;
    }

    pre {
      background: #1e1b4b;
      color: #e0e7ff;
      border-radius: 6px;
      padding: 14px 16px;
      margin: 12px 0;
      overflow: hidden;
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      line-height: 1.5;
      white-space: pre-wrap;
      word-break: break-all;
    }
    pre code { background: none; border: none; padding: 0; color: inherit; font-size: inherit; }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 12px 0;
      font-size: 10pt;
    }
    th {
      background: #4f46e5;
      color: white;
      padding: 8px 12px;
      text-align: left;
      font-weight: 600;
    }
    td {
      padding: 7px 12px;
      border-bottom: 1px solid #e5e7eb;
      vertical-align: top;
    }
    tr:nth-child(even) td { background: #f8f7ff; }

    blockquote {
      border-left: 3px solid #6366f1;
      padding: 8px 14px;
      margin: 12px 0;
      background: #f5f3ff;
      border-radius: 0 6px 6px 0;
      color: #4338ca;
      font-style: italic;
    }

    hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 20px 0;
    }

    /* Footer */
    .footer {
      margin-top: 32px;
      padding-top: 10px;
      border-top: 1px solid #e5e7eb;
      font-size: 8pt;
      color: #9ca3af;
      text-align: center;
    }

    @page {
      margin: 20mm 15mm;
    }
    @media print {
      body { padding: 0; }
      .page { padding: 0; max-width: 100%; }
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="watermark">Generated by idiot ai • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
    ${htmlContent}
    <div class="footer">idiot ai — AI-generated document • ${new Date().toLocaleString()}</div>
  </div>
  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print()
      }, 300)
    }
  </script>
</body>
</html>`

    // Open in a new window for printing (works better than iframe on most browsers)
    const printWindow = window.open('', '_blank', 'width=900,height=700')
    if (!printWindow) {
      setStatus('idle')
      alert('Please allow popups for this site to download PDFs.')
      return
    }

    printWindow.document.write(fullHTML)
    printWindow.document.close()

    // Listen for when print dialog closes
    const timer = setInterval(() => {
      if (printWindow.closed) {
        clearInterval(timer)
        setStatus('done')
        setTimeout(() => setStatus('idle'), 2500)
      }
    }, 500)

    // Timeout fallback
    setTimeout(() => {
      setStatus('done')
      setTimeout(() => setStatus('idle'), 2500)
    }, 5000)

  }, [content, filename])

  return (
    <div className="mt-3 pt-3 border-t border-indigo-500/20">
      <button
        onClick={handleDownload}
        disabled={status === 'generating'}
        className={`group flex items-center gap-2.5 px-4 py-2.5 rounded-xl text-xs font-semibold transition-all duration-200 cursor-pointer select-none focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 ${
          status === 'done'
            ? 'bg-emerald-500/15 border border-emerald-500/30 text-emerald-400'
            : status === 'generating'
            ? 'bg-indigo-500/10 border border-indigo-400/20 text-indigo-300 cursor-not-allowed'
            : 'bg-indigo-500/10 border border-indigo-400/20 text-indigo-300 hover:bg-indigo-500/20 hover:border-indigo-400/40 hover:text-indigo-200 active:scale-95'
        }`}
        aria-label="Download this document as PDF"
        title="Opens a print dialog to save as PDF"
      >
        {status === 'generating' ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin" />
        ) : status === 'done' ? (
          <CheckCircle2 className="h-3.5 w-3.5" />
        ) : (
          <FileDown className="h-3.5 w-3.5 group-hover:translate-y-0.5 transition-transform" />
        )}
        <span>
          {status === 'generating' ? 'preparing pdf...' : status === 'done' ? 'pdf ready!' : 'download as pdf'}
        </span>
      </button>
      <p className="mt-1.5 text-[10px] text-indigo-400/50 pl-0.5">
        opens a print dialog — choose "save as pdf"
      </p>
    </div>
  )
}

// ─── Minimal markdown → HTML converter ────────────────────────────────────────
// We use a simple regex-based approach since react-markdown is client-side only
// and we need server-compatible HTML for the print window

function markdownToHTML(md: string): string {
  let html = md
    // Escape any existing HTML
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')

  // Code blocks (``` ```)
  html = html.replace(/```[\w]*\n([\s\S]*?)```/g, (_, code) =>
    `<pre><code>${code.trim()}</code></pre>`
  )

  // Inline code (`code`)
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')

  // HR (--- or ***)
  html = html.replace(/^[-*]{3,}\s*$/gm, '<hr />')

  // Headings
  html = html.replace(/^#### (.+)$/gm, '<h4>$1</h4>')
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>')
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>')
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>')

  // Blockquotes
  html = html.replace(/^&gt; (.+)$/gm, '<blockquote>$1</blockquote>')

  // Bold (**text** or __text__)
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/__(.+?)__/g, '<strong>$1</strong>')

  // Italic (*text* or _text_)
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>')
  html = html.replace(/_(.+?)_/g, '<em>$1</em>')

  // Tables (basic)
  html = html.replace(/((?:\|.+\|\n)+)/g, (table) => {
    const rows = table.trim().split('\n').filter(r => !r.match(/^\|[-:| ]+\|$/))
    if (rows.length < 1) return table
    const [header, ...body] = rows
    const ths = header.split('|').filter(Boolean).map(c => `<th>${c.trim()}</th>`).join('')
    const trs = body.map(row =>
      `<tr>${row.split('|').filter(Boolean).map(c => `<td>${c.trim()}</td>`).join('')}</tr>`
    ).join('\n')
    return `<table><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`
  })

  // Unordered lists
  html = html.replace(/((?:^[-*+] .+\n?)+)/gm, (list) => {
    const items = list.trim().split('\n').map(l => `<li>${l.replace(/^[-*+] /, '').trim()}</li>`).join('')
    return `<ul>${items}</ul>`
  })

  // Ordered lists
  html = html.replace(/((?:^\d+\. .+\n?)+)/gm, (list) => {
    const items = list.trim().split('\n').map(l => `<li>${l.replace(/^\d+\. /, '').trim()}</li>`).join('')
    return `<ol>${items}</ol>`
  })

  // Paragraphs — wrap lines that aren't already wrapped in block tags
  html = html.replace(/^(?!<[houpbtr]|<\/|$)(.+)$/gm, '<p>$1</p>')

  // Clean up multiple blank lines
  html = html.replace(/\n{3,}/g, '\n\n')

  return html
}
